DeepSourceCorp/cli

.circleci/config.yml, git.go
For every PR `Travis` creates a merge commit, and the Head, as well as commit of the build, is this merge commit.
Now, the DeepSource check is created for the actual HEAD commit of the PR, hence there is a commit mismatch and the artifact push is not successful. Hence the `Test Coverage` analyzer is never triggered.
This PR fixes this.
Circle Ci does not have this complication. It works with forks. Verified.
=> Make analysis run on Travis Pull Requests

cmd/deepsource/main.go
Goreleaser already supplies a `version` [ldflag](https://goreleaser.com/environment/#using-the-mainversion), therefore it will be better to use it instead of setting the version ourselves everytime.
=> Use goreleaser supplied version flag

goreleaser.yaml
Post the publishing of the tap, the CLI can be installed using `brew` using the following command :
```
brew install deepsourcelabs/cli/deepsource
```
OR
```
brew tap deepsourcelabs/cli
brew install deepsource
```
The tap will be published in https://github.com/deepsourcelabs/homebrew-cli
=> Add goreleaser workflow to publish homebrew tap

command/report/constants.go, command/report/query.go, command/report/report.go, go.mod, go.sum
Depends on https://github.com/deepsourcelabs/svalbard/pull/1405.
Related: https://github.com/deepsourcelabs/docs-next/pull/53
=> PLT-2365: Increase limit of uploads to 20 MB

goreleaser.yaml
Goreleaser now allows pushing homebrew taps to branches other than the default branch. [Ref](https://goreleaser.com/customization/homebrew/).
Pushing to a different branch will help to verify the changes being pushed and then a pull request can be created in the [homebrew tap repository](https://github.com/deepsourcelabs/homebrew-cli) to merge the changes to master.
=> chore: push homebrew tap to branch other than master

command/repo/status/status.go, utils/fetch_remote.go, utils/fetch_remote_test.go, utils/remote_resolver.go
The current method of extracting owners from remote URLs doesn't work with remote URLs having a PAT in it, for example:
`https://username:<access_token>@github.com/username/repo`
This can be improved by using a regular expression like [this](https://regex101.com/r/xcIeR2/1), which can extract owner names from both type of remote URLs, as shown [here](https://regex101.com/r/xcIeR2/1).
=> fix(utils): add support for PAT based remote URLs

command/issues/list/list.go, command/issues/list/types.go, deepsource/issues/issues_list.go
* add `--json` flag
* add `--output` flag
* add custom types for marshaling to JSON
* add helper utilities for JSON conversion
=> feat(issues): add support for exporting issues to JSON

command/issues/list/list.go, command/issues/list/list_test.go, command/issues/list/testdata/test.sarif, command/issues/list/testdata/test_multi.sarif, go.mod, go.sum
Related: #95 
* add SARIF exporter
=> feat(issues): add support for exporting issues to SARIF

.github/workflows/CI.yml, Makefile, command/issues/list/list.go, command/report/tests/init_test.go, command/report/tests/report_workflow_test.go
=> fix: fix test coverage command to send data for entire package

command/report/git.go
=> fix: walk the directory for .git folder to fetch HEAD commit OID

config/config_test.go, go.mod
Closes #120.
Add tests for `config` package.
=> tests(config): add tests for config

command/auth/login/login.go, command/auth/refresh/refresh.go, command/auth/status/status.go, command/config/generate/generate.go, command/issues/list/list.go, command/repo/status/status.go, command/repo/view/view.go, command/report/report.go, go.mod, go.sum, utils/colors.go
Closes: #121
Adds `heredoc` for CLI documentation.
=> feat(*): use heredoc for adding CLI documentation

utils/remote_resolver_test.go
Closes: #122.
Adds tests for `remote_resolver` utility.
=> tests(utils): add tests for remote resolver

goreleaser.yaml
Adds support to build Windows binaries through GoReleaser.
Closes: #114
=> ci(release): add Windows support

analyzers/backend/docker/build.go, analyzers/backend/docker/pull.go, analyzers/backend/docker/utils.go, command/analyzer/dryrun/run.go, command/analyzer/dryrun/utils.go, command/analyzer/verify/build.go, utils/spinner.go
Adds a `--image-name` flag for running analyzers.
Example usage:
```sh
deepsource analyzer dry-run --image-name burntcarrot/2do-checker:latest
```
Screencast: https://asciinema.org/a/HzbEWDOm6W7h0ImKSyQW9yLQy
=> feat(backend/docker): add --image-name flag for running analyzers

.gitignore, goreleaser.yaml, scripts/gen-completions.sh
This adds a hook for `goreleaser` which will install the completions using `cobra` and Homebrew will pick them up when installing.
=> feat: provide Homebrew completions

command/report/query.go, command/report/report.go, command/report/tests/init_test.go, deepsource/tests/init_test.go
=> chore: add `--skip-verify` flag to skip SSL certificates verification while reporting test coverage

command/report/report.go
This is required for adding their support in the test-coverage analyzer.
=> feat: Whitelist keys for Swift and Kotlin

goreleaser.yaml
Removes the deprecated `replacements` field from the `goreleaser.yaml` file.
Ref: https://goreleaser.com/deprecations/#archivesreplacements
=> fix: remove deprecated field from goreleaser file

goreleaser.yaml
Since we now use zstd in CLI, we would need to enable CGO in the goreleaser config.
=> chore: enable cgo in goreleaser

.github/workflows/release.yml, .gitmodules, Makefile, go.mod, goreleaser.yaml, scripts/gen-completions.sh
Fixes the Goreleaser pipeline for CGO builds. We need CGO in CLI now since we compress the artifacts using zstd. This PR introduces [goreleaser-cross](https://github.com/goreleaser/goreleaser-cross) docker image to build the binaries for linux, darwin and windows operating systems and removes BSD based OS support since its not supported in cross compilation.
=> fix: fix goreleaser pipeline for CGO enabled builds

.gitignore
Adds `.release-env` to `.gitignore` for Goreleaser to not throw `Git is in a dirty state` error.
=> fix: add `.release-env` to .gitignore

goreleaser.yaml
Changes the homebrew tap org to DeepSourceCorp. The tap is located at [DeepSourceCorp/homebrew-cli](https://github.com/DeepSourceCorp/homebrew-cli)
=> chore: change homebrew tap organization to DeepSourceCorp

command/report/git.go, command/report/report.go
This broke reporting workflow in a case where an artifact was being reported from a docker container. Previously, Fetching HEAD manually was done in the end, after checking all env variables. In the last change, we were doing an early exit when the `git rev-parse` command threw an error, not allowing the flow to reach extracting git commit from env variable set in the docker container.
This change restores the previous workflow.
=> hotfix: don't early exit with error if root is not a git dir

goreleaser.yaml
This fixes the `Errno::ENOENT: No such file or directory - completions/deepsource.*` issue when installing using homebrew.
=> fix: include completions/ dir in releases

.github/workflows/CI.yml, utils/fetch_oidc_token_test.go
- remove `DEEPSOURCE_DSN` from env
- add required permissions for getting OIDC token
- change cli command to use oidc instead
- fix oidc tests
=> chore: use oidc to report coverage

.deepsource.toml, configvalidator/analyzer_config_validator.go, configvalidator/config_validator.go, configvalidator/config_validator_test.go, configvalidator/transformer_config_validator.go, configvalidator/types.go
Signed-off-by: Sourya Vatsyayan <sourya@deepsource.io>
=> fix: make enabled optional in .deepsource.toml
