init.go

Signed-off-by: Jai <jai@deepsource.io>

Fix DSN starts with bug and add newline to errors

---

init.go

Signed-off-by: Jai <jai@deepsource.io>

Update GraphQL query route to /graphql/cli/

---

.deepsource.toml
README.md

Signed-off-by: Jai <jai@deepsource.io>

Add DeepSource go analysis

---

.circleci/config.yml
.clabot
go.mod

Signed-off-by: Jai <jai@deepsource.io>

Init go mod and update go version

---

git.go

Signed-off-by: Sourya Vatsyayan <sourya@deepsource.io>

[Fix #21] Fix commit sha in case of github actions PR

---

go.mod
goreleaser.yaml
init.go

Add sentry integration

---

goreleaser.yaml

Add version ldflag to goreleaser config

---

goreleaser.yaml

🚀 Support darwin/arm64 and other arm architectures

---

.github/workflows/release.yml

Wokflow to make a release on every new tag pushed.

Add github action workflow for goreleaser

---

.github/workflows/release.yml
goreleaser.yaml

Use deepsourcebot for pushing taps

---

.github/workflows/release.yml
goreleaser.yaml

Fix token retrieval

---

.github/workflows/release.yml
goreleaser.yaml

Remove specific permissions and test brew tap

---

.deepsource.toml
command/config/validate/validate.go
configvalidator/analyzer_config_validator.go
configvalidator/analyzer_config_validator_test.go
configvalidator/config_validator.go
configvalidator/config_validator_test.go
configvalidator/generic_config_validator.go
configvalidator/generic_config_validator_test.go
configvalidator/transformer_config_validator.go
configvalidator/transformer_config_validator_test.go
configvalidator/types.go
go.mod
go.sum

Adds unit tests to the package which does config validation.

test: add unit tests to configvalidator package

---

command/auth/login/login.go
command/auth/login/login_flow.go
command/auth/refresh/refresh.go
command/config/generate/analyzers_input.go
command/config/generate/generate.go
command/config/generate/input.go
command/config/generate/transformers_input.go
command/config/validate/validate.go
command/issues/list/list.go
command/repo/status/status.go
command/repo/view/view.go
config/config.go
configvalidator/analyzer_config_validator.go
configvalidator/config_validator_test.go
configvalidator/transformer_config_validator.go
deepsource/client.go
utils/fetch_analyzers_transformers.go

Preview (for the interactive mode and enterprise changes) : https://asciinema.org/a/SCzl5kOTUUWFQKbitGorEkBQJ
This PR:
* Implements changes for the CLI to support enterprise instance
* Adds an interactive mode for logging into the CLI

feat: support enterprise server

---

.github/workflows/gitopia-mirror.yml
README.md

chore: fix gitopia action and modify README

---

goreleaser.yaml

fix: use a single branch to push taps

---

.github/workflows/CI.yml
Makefile
README.md

chore: configure test-coverage analyzer

---

README.md

Fixes the logo URL and adds note regarding API changes.

fix: change logo URL and add note

---

command/auth/login/login.go
command/auth/login/pat_login_flow.go
config/config.go
deepsource/analyzers/queries/get_analyzers.go
deepsource/issues/queries/list_file_issues.go
deepsource/issues/queries/list_issues.go
deepsource/repository/queries/repository_status.go
deepsource/transformers/queries/get_transformers.go

Related: #100 
* add new PAT-based login flow
* refactor login command and config

feat(auth/login): add support for passing PAT using a flag

---

command/issues/list/list.go
command/issues/list/list_test.go

Related: #94 
* add support for CSV export
* add tests for CSV and JSON exporters

feat(issues): add support for exporting issues to CSV

---

go.mod
go.sum

As discussed, upgrading the `cobra` dependency to the latest version.
resolve: #170

build(deps): upgrade `cobra` to `v1.5.0`

---

analyzers/diagnostics/diagnostics.go
analyzers/diagnostics/diagnostics_test.go
analyzers/diagnostics/testdata/test_constructdiagnostics/multiple_diagnostics/multiple_files/test_want.toml
analyzers/diagnostics/testdata/test_constructdiagnostics/multiple_diagnostics/single_file/test_want.toml
analyzers/diagnostics/testdata/test_constructdiagnostics/single_diagnostic/multiple_files/test_want.toml
analyzers/diagnostics/testdata/test_constructdiagnostics/single_diagnostic/single_file/test_want.toml
analyzers/diagnostics/testdata/test_getdiagnostics/less_lines/test_want.toml
analyzers/diagnostics/testdata/test_getdiagnostics/multiple_errors/test_want.toml
analyzers/diagnostics/testdata/test_getdiagnostics/single_error/test_want.toml
analyzers/validator/validator.go
command/analyzer/verify/verify.go

Adds support for reporting diagnostics in issue TOML files.
Screencast (updated): https://asciinema.org/a/GyxAbURDBY8GJbJWl6peJBbmZ

feat: add diagnostic reporting in issue TOML files

---

command/report/query.go

chore: remove stale log

---

.clabot

Add Subham to contributors list.

chore: add Subham to contributors

---

command/report/report.go

if `Message` is empty, don't display it.

Only show message when present

---

command/report/constants.go
command/report/report.go
command/report/types.go

This way it's backwards compatible.

Fallback for GraphQL query without message

---

.github/workflows/CI.yml

`test-coverage-action` is deprecated.

Use CLI itself for test coverage reporting

---

.clabot

Adds vishesh-deepsource to contributors list for CLI.

Add vishesh to contributors

---

README.md

Docs: Fixes broken CLI documentation link

Docs: Fix CLI Docs Link on README.md

---

.github/workflows/release.yml

Fix the command to append environment variables to a file.

fix: fix release env vars append command

---

goreleaser.yaml

https://goreleaser.com/customization/homebrew/?h=brew

fix: homebrew release with multiple archives and same os/arch
